"""Refactor completo a español

Revision ID: d601b21b1aee
Revises: 
Create Date: 2025-12-06 01:42:15.239236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd601b21b1aee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('moneda', sa.String(), nullable=True),
    sa.Column('impuesto_porcentaje', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('nombre_empresa', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email_contacto', sa.String(), nullable=True),
    sa.Column('notif_stock_critico', sa.Boolean(), nullable=True),
    sa.Column('notif_reporte_diario', sa.Boolean(), nullable=True),
    sa.Column('notif_sugerencias_ia', sa.Boolean(), nullable=True),
    sa.Column('notif_margen_bajo', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('recurso', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_index(op.f('ix_permisos_nombre'), 'permisos', ['nombre'], unique=True)
    op.create_table('restaurantes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=True),
    sa.Column('propietario_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], name='fk_restaurante_propietario', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantes_id'), 'restaurantes', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('unidades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('unidad_base_id', sa.String(), nullable=True),
    sa.Column('factor_conversion', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unidad_base_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_codigo'), 'unidades', ['codigo'], unique=True)
    op.create_index(op.f('ix_unidades_id'), 'unidades', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=False),
    sa.Column('contrasena_hash', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('es_superusuario', sa.Boolean(), nullable=True),
    sa.Column('sucursal_default_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_default_id'], ['sucursales.id'], name='fk_usuario_sucursal_default', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_table('permisos_rol',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rol_id', sa.String(), nullable=False),
    sa.Column('permiso_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id')
    )
    op.create_index(op.f('ix_permisos_rol_id'), 'permisos_rol', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nombre_contacto', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('zona', sa.String(), nullable=True),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('terminos_pago', sa.String(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('zona', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('horarios_atencion', sa.JSON(), nullable=True),
    sa.Column('restaurante_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_table('items_inventario',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('unidad_id', sa.String(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('stock_maximo', sa.Float(), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.String(), nullable=True),
    sa.Column('sucursal_id', sa.String(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('codigo_barras', sa.String(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('puntaje_popularidad', sa.Float(), nullable=True),
    sa.Column('factor_estacional', sa.JSON(), nullable=True),
    sa.Column('pronostico_demanda', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_inventario_categoria'), 'items_inventario', ['categoria'], unique=False)
    op.create_index(op.f('ix_items_inventario_codigo_barras'), 'items_inventario', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_items_inventario_id'), 'items_inventario', ['id'], unique=False)
    op.create_index(op.f('ix_items_inventario_nombre'), 'items_inventario', ['nombre'], unique=False)
    op.create_index(op.f('ix_items_inventario_ultima_actualizacion'), 'items_inventario', ['ultima_actualizacion'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_orden', sa.String(), nullable=False),
    sa.Column('proveedor_id', sa.String(), nullable=False),
    sa.Column('sucursal_id', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('fecha_entrega_esperada', sa.DateTime(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.String(), nullable=True),
    sa.Column('aprobado_por_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_compra_fecha_creacion'), 'ordenes_compra', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_id'), 'ordenes_compra', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_numero_orden'), 'ordenes_compra', ['numero_orden'], unique=True)
    op.create_table('promociones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_descuento', sa.String(), nullable=False),
    sa.Column('valor_descuento', sa.Float(), nullable=False),
    sa.Column('compra_minima', sa.Float(), nullable=True),
    sa.Column('descuento_maximo', sa.Float(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('aplicable_a', sa.String(), nullable=True),
    sa.Column('ids_aplicables', sa.JSON(), nullable=True),
    sa.Column('sucursal_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promociones_id'), 'promociones', ['id'], unique=False)
    op.create_table('recetas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('subcategoria', sa.String(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('margen', sa.Float(), nullable=False),
    sa.Column('tiempo_preparacion', sa.Integer(), nullable=True),
    sa.Column('porciones', sa.Integer(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('sucursal_id', sa.String(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('puntaje_popularidad', sa.Float(), nullable=True),
    sa.Column('version_actual', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_categoria'), 'recetas', ['categoria'], unique=False)
    op.create_index(op.f('ix_recetas_id'), 'recetas', ['id'], unique=False)
    op.create_index(op.f('ix_recetas_nombre'), 'recetas', ['nombre'], unique=False)
    op.create_table('usuarios_rol',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('rol_id', sa.String(), nullable=False),
    sa.Column('sucursal_id', sa.String(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('asignado_por_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'rol_id', 'sucursal_id')
    )
    op.create_index(op.f('ix_usuarios_rol_id'), 'usuarios_rol', ['id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_venta', sa.String(), nullable=True),
    sa.Column('sucursal_id', sa.String(), nullable=False),
    sa.Column('numero_mesa', sa.String(), nullable=True),
    sa.Column('mesero_id', sa.String(), nullable=True),
    sa.Column('tipo_venta', sa.String(), nullable=False),
    sa.Column('servicio_delivery', sa.String(), nullable=True),
    sa.Column('nombre_cliente', sa.String(), nullable=True),
    sa.Column('telefono_cliente', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('monto_descuento', sa.Float(), nullable=True),
    sa.Column('impuesto', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mesero_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_fecha_creacion'), 'ventas', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_index(op.f('ix_ventas_numero_venta'), 'ventas', ['numero_venta'], unique=True)
    op.create_table('descuentos_venta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venta_id', sa.String(), nullable=False),
    sa.Column('promocion_id', sa.String(), nullable=True),
    sa.Column('tipo_descuento', sa.String(), nullable=False),
    sa.Column('monto_descuento', sa.Float(), nullable=False),
    sa.Column('razon', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['promocion_id'], ['promociones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descuentos_venta_id'), 'descuentos_venta', ['id'], unique=False)
    op.create_table('historial_costos_inventario',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_inventario_id', sa.String(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('proveedor_id', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('razon', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_inventario_id'], ['items_inventario.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_costos_inventario_fecha'), 'historial_costos_inventario', ['fecha'], unique=False)
    op.create_index(op.f('ix_historial_costos_inventario_id'), 'historial_costos_inventario', ['id'], unique=False)
    op.create_index(op.f('ix_historial_costos_inventario_item_inventario_id'), 'historial_costos_inventario', ['item_inventario_id'], unique=False)
    op.create_table('ingredientes_receta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('receta_id', sa.String(), nullable=False),
    sa.Column('item_inventario_id', sa.String(), nullable=True),
    sa.Column('nombre_ingrediente', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('unidad_id', sa.String(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_inventario_id'], ['items_inventario.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_receta_id'), 'ingredientes_receta', ['id'], unique=False)
    op.create_table('items_orden_compra',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orden_compra_id', sa.String(), nullable=False),
    sa.Column('item_inventario_id', sa.String(), nullable=True),
    sa.Column('nombre_item', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('cantidad_recibida', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_inventario_id'], ['items_inventario.id'], ),
    sa.ForeignKeyConstraint(['orden_compra_id'], ['ordenes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_orden_compra_id'), 'items_orden_compra', ['id'], unique=False)
    op.create_table('items_venta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venta_id', sa.String(), nullable=False),
    sa.Column('receta_id', sa.String(), nullable=True),
    sa.Column('nombre_item', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_venta_id'), 'items_venta', ['id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_inventario_id', sa.String(), nullable=False),
    sa.Column('sucursal_id', sa.String(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('referencia_id', sa.String(), nullable=True),
    sa.Column('tipo_referencia', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_inventario_id'], ['items_inventario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_fecha_creacion'), 'movimientos_inventario', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_id'), 'movimientos_inventario', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_item_inventario_id'), 'movimientos_inventario', ['item_inventario_id'], unique=False)
    op.create_table('versiones_receta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('receta_id', sa.String(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('margen', sa.Float(), nullable=False),
    sa.Column('tiempo_preparacion', sa.Integer(), nullable=True),
    sa.Column('porciones', sa.Integer(), nullable=False),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('razon_cambio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versiones_receta_id'), 'versiones_receta', ['id'], unique=False)
    op.create_index(op.f('ix_versiones_receta_receta_id'), 'versiones_receta', ['receta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versiones_receta_receta_id'), table_name='versiones_receta')
    op.drop_index(op.f('ix_versiones_receta_id'), table_name='versiones_receta')
    op.drop_table('versiones_receta')
    op.drop_index(op.f('ix_movimientos_inventario_item_inventario_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_fecha_creacion'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_items_venta_id'), table_name='items_venta')
    op.drop_table('items_venta')
    op.drop_index(op.f('ix_items_orden_compra_id'), table_name='items_orden_compra')
    op.drop_table('items_orden_compra')
    op.drop_index(op.f('ix_ingredientes_receta_id'), table_name='ingredientes_receta')
    op.drop_table('ingredientes_receta')
    op.drop_index(op.f('ix_historial_costos_inventario_item_inventario_id'), table_name='historial_costos_inventario')
    op.drop_index(op.f('ix_historial_costos_inventario_id'), table_name='historial_costos_inventario')
    op.drop_index(op.f('ix_historial_costos_inventario_fecha'), table_name='historial_costos_inventario')
    op.drop_table('historial_costos_inventario')
    op.drop_index(op.f('ix_descuentos_venta_id'), table_name='descuentos_venta')
    op.drop_table('descuentos_venta')
    op.drop_index(op.f('ix_ventas_numero_venta'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha_creacion'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_usuarios_rol_id'), table_name='usuarios_rol')
    op.drop_table('usuarios_rol')
    op.drop_index(op.f('ix_recetas_nombre'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_categoria'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_promociones_id'), table_name='promociones')
    op.drop_table('promociones')
    op.drop_index(op.f('ix_ordenes_compra_numero_orden'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_id'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_fecha_creacion'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_items_inventario_ultima_actualizacion'), table_name='items_inventario')
    op.drop_index(op.f('ix_items_inventario_nombre'), table_name='items_inventario')
    op.drop_index(op.f('ix_items_inventario_id'), table_name='items_inventario')
    op.drop_index(op.f('ix_items_inventario_codigo_barras'), table_name='items_inventario')
    op.drop_index(op.f('ix_items_inventario_categoria'), table_name='items_inventario')
    op.drop_table('items_inventario')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_permisos_rol_id'), table_name='permisos_rol')
    op.drop_table('permisos_rol')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_unidades_id'), table_name='unidades')
    op.drop_index(op.f('ix_unidades_codigo'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_restaurantes_id'), table_name='restaurantes')
    op.drop_table('restaurantes')
    op.drop_index(op.f('ix_permisos_nombre'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
